# Generated by Django 4.2 on 2023-11-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
