# Generated by Django 4.2 on 2023-11-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_rename_nombre_autor_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='autor', max_length=25),
            preserve_default=False,
        ),
    ]
