# Generated by Django 4.2 on 2023-11-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_autor_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='seudonimo',
            field=models.CharField(blank=True, max_length=50, verbose_name='seudonimo'),
        ),
    ]
