# Generated by Django 4.2 on 2023-11-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lector',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AlterField(
            model_name='lector',
            name='edad',
            field=models.PositiveBigIntegerField(),
        ),
    ]
