# Generated by Django 4.2 on 2023-11-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_rename_nombre_lector_nombres_alter_lector_edad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
    ]
