# Generated by Django 4.2 on 2023-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='nulo', max_length=50),
            preserve_default=False,
        ),
    ]
