# Generated by Django 4.2.6 on 2023-11-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fecha'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
